### ISSUE TITLE
support generate several sprites

### ISSUE THREAD

**Issue by kairyou** [aslansky/css-sprite#60] opened 2015-03-20 05:13 UTC
Please add a option for generate several sprites, e.g., generate icons-header.png, icons-footer.png and _icons.scss, or icons-header.png + icons-header.scss and icons-footer.png + _icons-footer.scss.
```javascript
sprite.create({
	src: ['./src/**/*.png'], // src: ['./src/header/*.png', './src/footer/*.png']
	out: './dist/img',
	name: 'icons', 
	style: './dist/scss/_icons.scss',
	cssPath: '../img/',
	processor: 'scss',
});
```

**Comment by aslansky** [comment] 2015-04-01 15:10
Seems to be a duplicate of #21

**Closed by aslansky** 2015-04-01 15:10 UTC
Labels: duplicate, enhancement
